library(tidyverse)
library(dplyr)
library(lubridate)
library(readxl)
rm(list=ls())

setwd("D:/DATA 331/Final Project")

df_scan_ladybug <- read.csv("Scan Ladybug Data.csv")
df_ladybug <- read_excel("Ladybug Data.xlsx", sheet = 1) 

unique(df_ladybug$collector)
df_ladybug$collector <- str_replace(df_ladybug$collector, "J Hughes", "J. Hughes")
df_ladybug$collector <- str_replace(df_ladybug$collector, "Jack Hughes", "J. Hughes")
df_ladybug$collector <- str_replace(df_ladybug$collector, "j. Hughes", "J. Hughes")
df_ladybug$collector <- str_replace(df_ladybug$collector, "J. hughes", "J. Hughes")
df_ladybug$collector <- str_replace(df_ladybug$collector, "jack hughes", "J. Hughes")
df_ladybug$collector <- str_replace(df_ladybug$collector, "J. Hughees", "J. Hughes")
df_ladybug$collector <- str_replace(df_ladybug$collector, "j. hughes", "J. Hughes")
df_ladybug$collector <- str_replace(df_ladybug$collector, "Olivia Ruffatto", "O. Ruffatto")
df_ladybug$collector <- str_replace(df_ladybug$collector, "O. ruffatto", "O. Ruffatto")
df_ladybug$collector <- str_replace(df_ladybug$collector, "o. Ruffatto", "O. Ruffatto")
df_ladybug$collector <- str_replace(df_ladybug$collector, "Olivia ruffatto", "O. Ruffatto")
df_ladybug$collector <- str_replace(df_ladybug$collector, "o. ruffattto", "O. Ruffatto")
df_ladybug$collector <- str_replace(df_ladybug$collector, "o. ruffatto", "O. Ruffatto")
df_ladybug$collector <- str_replace(df_ladybug$collector, "OliviaRuffatto", "O. Ruffatto")
df_ladybug$collector <- str_replace(df_ladybug$collector, "m gorsegner", "M. Gorsegner")
df_ladybug$collector <- str_replace(df_ladybug$collector, "m. gorsegner", "M. Gorsegner")
df_ladybug$collector <- str_replace(df_ladybug$collector, "M.Gorsegner", "M. Gorsegner")
df_ladybug$collector <- str_replace(df_ladybug$collector, "Marissa Gorsegner", "M. Gorsegner")
df_ladybug$collector <- str_replace(df_ladybug$collector, "M. gorsegner", "M. Gorsegner")
df_ladybug$collector <- str_replace(df_ladybug$collector, "v. cervantes", "V. cervantes")
df_ladybug$collector <- str_replace(df_ladybug$collector, "Veronica Cervatnes", "V. cervantes")
df_ladybug$collector <- str_replace(df_ladybug$collector, "Veronica Cervantes", "V. cervantes")
df_ladybug$collector <- str_replace(df_ladybug$collector, "V. Cervantes", "V. cervantes")
df_ladybug$collector <- str_replace(df_ladybug$collector, "V. cervantes", "V. cervantes")
df_ladybug$collector <- str_replace(df_ladybug$collector, "V.Cervantes", "V. cervantes")
df_ladybug$collector <- str_replace(df_ladybug$collector, "v cervantes", "V. cervantes")

unique(df_ladybug$Species)
df_ladybug$Species <- str_replace(df_ladybug$Species, "Propylea quatuordecimpuncata", "Propylea quatuordecimpunctata")
df_ladybug$Species <- str_replace(df_ladybug$Species, "Harmonia axyrisis", "Harmonia axyridis")
df_ladybug$Species <- str_replace(df_ladybug$Species, "harmonia axyridis", "Harmonia axyridis")
df_ladybug$Species <- str_replace(df_ladybug$Species, "harmonia axyrids", "Harmonia axyridis")
df_ladybug$Species <- str_replace(df_ladybug$Species, "Harminia axyridis", "Harmonia axyridis")
df_ladybug$Species <- str_replace(df_ladybug$Species, "Colemegilla maculata", "Coleomegilla maculata")
df_ladybug$Species <- str_replace(df_ladybug$Species, "coleomegilla maculata", "Coleomegilla maculata")
df_ladybug$Species <- str_replace(df_ladybug$Species, "Cycloneda munda", "Cycloneda Munda")
df_ladybug$Species <- str_replace(df_ladybug$Species, "cycloneda munda", "Cycloneda Munda")
df_ladybug$Species <- str_replace(df_ladybug$Species, "coccinella septempunctata", "Coccinella Septempunctata")
df_ladybug$Species <- str_replace(df_ladybug$Species, "Coccinella septempunctata", "Coccinella Septempunctata")
df_ladybug$Species <- str_replace(df_ladybug$Species, "hippodamia parenthesis", "Hippodamia parenthesis")
df_ladybug$Species <- str_replace(df_ladybug$Species, "Hippodamia covergence", "Hippodamia convergens")
df_ladybug$Species <- str_replace(df_ladybug$Species, "hippodamia convergens", "Hippodamia convergens")
df_ladybug$Species <- str_replace(df_ladybug$Species, "Coccinella septempunctata", "Coccinella Septempunctata")
df_ladybug$Species <- str_replace(df_ladybug$Species, "Coccinella semtempuncata", "Coccinella Septempunctata")

sally